// AUTO-GENERATED by `ondajs add` — do not edit manually.
// Re-run `bunx ondajs add <slug>` to update.
// Pass `--no-barrel` to opt out; delete this file + .ondajs-installed.json
// to disable barrel management going forward.

export const ondaRegistry = {} as const;
